### ISSUE TITLE
graphml labels are not drawable

### ISSUE THREAD

**Issue by jdeantoni** [graphia-app/graphia#10]
Hi,

I have a graphML file with label (not node id) like the one from the graphML spec from section 2.4.3 (represented on section 2.4.1) here: http://graphml.graphdrawing.org/primer/graphml-primer.html

I'm not able to show the label neither on edges nor nodes.

What am I missing ?

**Comment by timangus** [comment]
GraphML is a pretty loose format. The file you have might be encoding the labels in an unusual way. If you could supply it I can take a look when I get a chance...

**Comment by jdeantoni** [comment]
Hi, and thanks for your answer. [Here](https://www.i3s.unice.fr/~deantoni/graphMLExample/Distributed.lf_statespace.graphml) is a small graphml graph with attribute (label is one of them):
 
Also, here is one representation of this graph:
![image](https://user-images.githubusercontent.com/6162718/107475332-37b63b00-6b74-11eb-9056-59839e0c74da.png)

I hope it helps
thanks for graphia

**Comment by herrmann** [comment]
It's currently using the node's ID as the label: https://github.com/graphia-app/graphia/blob/afb8862879580031491d6f9d3fb4881913ddac2b/source/shared/loading/graphmlparser.cpp#L131

**Comment by timangus** [comment]
> Hi, and thanks for your answer. [Here](https://www.i3s.unice.fr/~deantoni/graphMLExample/Distributed.lf_statespace.graphml)

In your example it appears like the label attribute is not introduced in the header of the graphml file. Specifically you have `<key id="labels.visibleIds" attr.name="Visible Labels" for="node" attr.type="string">` where it should probably read `<key id="label" attr.name="Visible Labels" for="node" attr.type="string">`. If I change this it can be displayed using a text visualisation.

![image](https://user-images.githubusercontent.com/3159586/108346281-1dfd9f00-71d7-11eb-972f-d30d3bbb2d7e.png)

**Comment by jdeantoni** [comment]
Hi ! Thanks a lot I'll setup a script to modify the graphml in output of the other tool :)
thanks again
