### ISSUE TITLE
Unable to open CSV file as adjacency matrix

### ISSUE THREAD

**Issue by hadisfr** [graphia-app/graphia#12]
Hi!
I'm trying to open an almost large _CSV_ adjacency matrix file, which has got no header, and has got a pair like `a,b` in each row denoting an edge from node `a` to node `b`.
Whenever I try to open this file, Graphia considers it as a correlational matrix and fails to open it.
I tried selecting _Adjacency Matrix CSV File_ while opening the file but same thing happened.
What should I do?
P.S. I'm using Graphia 2.2 on Linux Ubuntu.

**Comment by timangus** [comment]
Coincidentally I've been working on the adjacency matrix loading code recently. You could try a newer build from https://graphia.dev/. Failing that, if you can supply the file that's causing the problem I'll take a look when I get a chance.

**Comment by hadisfr** [comment]
I saw that commit but it seemed irrelevant to my problem to me.

I'll try the latest dev version. If it fails too, I'll send you a minimal file example.

Thanks for your effort!

**Comment by hadisfr** [comment]
OK. I tested with _dev-1041-g951b80e7_ and problem remains.
I tried to open [_graph.csv_](https://github.com/graphia-app/graphia/files/5955069/graph.csv.zip) file as *adjacency matrix*, which is expected to generate a graph like the one in [_graph.graphml_](https://github.com/graphia-app/graphia/files/5955071/graph.graphml.zip).
![graph](https://user-images.githubusercontent.com/24562441/107448038-15adc000-6b56-11eb-8870-04c6c1595ba5.png)
(Image is generated from _graphml_ file. It seems that Graphia ignores self loops.)
But Graphia always to open it as a *correlational matrix* and finally generates an empty graph.

**Comment by timangus** [comment]
I'm not really sure how you're expecting your csv to be interpreted, but that it not an adjacency matrix in the normal sense. Graphia expects a numerical matrix where the numbers indicate the weight of a relationship between the nodes represented by row and column headers. e.g.:

![image](https://user-images.githubusercontent.com/3159586/108347082-083ca980-71d8-11eb-893f-f5f705636a4b.png)
![image](https://user-images.githubusercontent.com/3159586/108347199-26a2a500-71d8-11eb-976e-fb4320396387.png)

**Comment by hadisfr** [comment]
I see. I don't know why I confused adjacency matrix with edge list. 🤦🏻‍♂️

And there is no way to import edge nodes via a csv adjacency matrix, am I right?

**Comment by timangus** [comment]
Not from a CSV, but you can use pairwise text files to load an edge list. It's just a text file with 2 or 3 columns, the first 2 being node identifiers and the (optional) 3rd being a weight.
