### ISSUE TITLE
Zoom into arbitrary parts of graph

### ISSUE THREAD

**Issue by hadisfr** [graphia-app/graphia#15]
Hi!
Is it possible to zoom into an arbitrary part of graph? Whenever I try to zoom in, Graphia zooms into centre of the graph.
I tried combinations of Ctrl/Alt/Shift while scrolling, and also tried to focus on a non-centric node of the graph, but I failed. I could not find anything related in the docs, too.

**Comment by timangus** [comment]
The tutorial (go to the Help menu) should help you understand how to navigate, but as your specific problem if you double click on a node it will become the new centre for rotation and zooming. Or you can right click and drag.
