### ISSUE TITLE
Q: how to enable visualization of edge direction?

### ISSUE THREAD

**Issue by nsajko** [graphia-app/graphia#22]
I loaded this simple digraph:

```
graph [
 Creator "me" directed 1 label "some graph"
  node [
   id 1
  ]
  node [
   id 2
  ]
  edge [
   source 1
   target 2
  ]
]
```

How do I tell Graphia to indicate each edge's direction while displaying the graph?

In case this feature is missing, is there at least some way to find an edge's direction by selecting an individual edge?

EDIT: the funny thing is, the Tutorial says that all edges have a direction in Graphia, while in reality none do.

**Comment by JDHarlingLee** [comment]
Hi @nsajko,

"View" -> "Show Edge Direction" - is that the feature you are looking for?

**Comment by nsajko** [comment]
> "View" -> "Show Edge Direction" - is that the feature you are looking for?

@JDHarlingLee thanks, but when I open the "View" drop-down menu, there is no option "Show Edge Direction".

I have the Graphia from latest master, should I be using the 2.2 tag instead?

**Comment by JDHarlingLee** [comment]
@nsajko - that's odd, it's not a new feature. I can confirm it definitely works in v2.2 with your example graph above, although the option does only appear when the graph is loaded.

**Comment by nsajko** [comment]
I figured out a piece of the puzzle: when I switch from Intel to NVIDIA graphics (this is on a laptop), the "Show Edge Direction" appears. You guys should probably document that, if it's not already documented.

**Comment by timangus** [comment]
I don't think the chipset selection on your laptop has any relevance here. The "Show Edge Direction" option shows up when you open a file that has directional edges. It's probably just a coincidence that you happened to change chipset at the same time you opened such a file. If that's not it, it'll be some kind of weird bug or interaction between your drivers/window manager/Qt/something else, that is outside the scope of what Graphia controls.
