### ISSUE TITLE
Selected Nodes Display

### ISSUE THREAD

**Issue by NotOneRing** [graphia-app/graphia#25]
Dear Contributors,

Sorry for the inconvenience I might cause.

I need a pretty simple function. To display the nodes I have prepared, I have those nodes in a text file, or I can manually input them. For example, if a graph has 9 nodes(1, 2, 3, 4, 5, 6, 7, 8, 9 ) and some edges between them, I want to know where the 3, 5, 7 nodes are, i.e. displaying 3, 5, 7 with a different color in the visualization. Is there any function like a filter that allows me to find out where those nodes are? Because when I have a large graph with thousands of nodes a want to know where they are, it's pretty difficult to manually pick them. Could you please kindly give me some help? 

Thanks so much for your time and great efforts!!!

Best regards,
Yours User

**Comment by timangus** [comment]
There are a number of things that might help;

- Graphia is primarily data driven so if you have some attribute on the nodes of interest (or can introduce an attribute in the source data), this can then be visualised by clicking `Add Visualisation`. e.g. if nodes 3, 5 and 7 are of interest you could add an attribute called 'interesting' or something similar and set its value to YES for said nodes.
- You can find using regular expressions so if you have nodes with the names 3, 5 and 7, if you initiate a search with Ctrl+F and type ^(3|5|7)$ this will select nodes that have exactly 3, 5 or 7 as the value for some attribute. This will highlight the nodes via the selection marker, which may be enough, depending on your needs.
- Finally, having made that selection, you can use the Bookmarks functionality to save and recall it, should you need to.

There is no means to manually highlight/visualise a selection for what it's worth as it's slightly against the ethos of the application (i.e. data driven), but it might be something I look into in the future, who knows.

BTW, the Discussions section is probably a better place for queries like this, Issues is more about reporting problems or submitting bug fixes etc.

HTH.
