### ISSUE TITLE
Failure to load Attributes from csv file

### ISSUE THREAD

**Issue by florian-huber** [graphia-app/graphia#46]
Thanks a lot for building this great tool!

When I try to add attributes to the graph via `Import Attributes from Table` I keep running into the error `Failed to Load xyz.csv` (even when changing separators/delimiters like comma, space, tab).

File looks roughly like this:
```
"Node Name", feature
"A", 5
"B", 3
"C", 3
...
```

As a workaround I currently merge all attributes into one graphml file, which works fine. But table imports would be nicer I guess.

**Comment by timangus** [comment]
Hmm, that fragment you posted there imports without any problems here. Perhaps you could attach the actual file you're experiencing the problem with (or some other broken test case if you can't attach the actual file), and we can go from there...
