### ISSUE TITLE
Please provide AppImage for download

### ISSUE THREAD

**Issue by probonopd** [graphia-app/graphia#5]
Hi, thanks for making an AppImage. Could you please provide the bare AppImage file without an archive around it?

https://github.com/graphia-app/graphia/releases/download/2.0/Graphia-2.0.tar.gz

The reasons are explained at https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages/cc2441518975caca23e9ce2dba6f08a22c678d1e#common-mistake.

Thank you very much for your consideration.

**Comment by timangus** [comment]
I appreciate the reasons for not archiving AppImages, but in our case it's not about setting the execute bit (though that's a minor side benefit.) The main reason is that we have an update system that will periodically download and replace the AppImage file. As such it doesn't make sense to have the version number in the AppImage file name as after the first update it would be permanently incorrect. Our AppImage doesn't have the version number in the file name; the point of archiving is to avoid this, while retaining the version information in the downloaded file name.

(I'm aware AppImage has its own update system, but we have an update mechanism that is shared between platforms. We want to avoid the overhead of using multiple update systems.)

**Comment by probonopd** [comment]
I see... and I can follow your reasoning. Apparently you are aware that you are trading off some AppImage benefits for having an update mechanism that is shared between platforms. That's a valid tradeoff. Maybe you might consider to provide an unpackaged AppImage file _in addition_ to the archived ones? In any case it's your decision of course, so feel free to close the ticket.
