### ISSUE TITLE
glibc version 

### ISSUE THREAD

**Issue by colindaven** [graphia-app/graphia#6]
Hi,

I'm wondering what Linux systems the Appimage has been tested on. It doesn't work on Ubuntu 1604.

Does it only work with GLIBC 2.27 ?

Thanks

```

davenpor@CS12035302b:~/programs/graphia$ ./Graphia.AppImage 
./Graphia.AppImage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by ./Graphia.AppImage)
./Graphia.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by ./Graphia.AppImage)
./Graphia.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by ./Graphia.AppImage)
./Graphia.AppImage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /tmp/.mount_Graphi0IPHT2/usr/bin/../lib/libthirdparty.so)
./Graphia.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.27' not found (required by /tmp/.mount_Graphi0IPHT2/usr/bin/../lib/libgssapi_krb5.so.2)




ldd --version
ldd (Ubuntu GLIBC 2.23-0ubuntu11.2) 2.23
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

**Comment by timangus** [comment]
It was built on 20.04 if I remember correctly, so it'll use the libc that's on there. We've since transitioned to using GitHub Actions and a 16.04 image, so hopefully the next release will work better for you.

**Comment by colindaven** [comment]
Ok, thanks for the tool and the quick answer!
Colin

**Comment by timangus** [comment]
2.1 may work better for you, I hope.

**Comment by jberryman** [comment]
I'm getting 

```
./Graphia.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by ./Graphia.AppImage)
./Graphia.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by ./Graphia.AppImage)
```

on 2.1 which IIUC means gcc-9 toolchain, which means debian bullseye (likewise for the Qt dependencies to build from source)... aaaand unfortunately the upgrade path to bullseye is [broken for me](https://salsa.debian.org/rpavlik/gcc-10-compat).

Is there any way to bundle libstdc++ in the AppImage somehow? I have no familiarity with appimage

**Comment by jberryman** [comment]
@timangus by the way if you want to document debian bullseye build instructions, `sudo apt install libqt5svg5-dev qtdeclarative5-dev qtbase5-dev` should get folks there (although I haven't been able to get a working build yet).

**Comment by timangus** [comment]
> Is there any way to bundle libstdc++ in the AppImage somehow? I have no familiarity with appimage

I think there was a patch to AppImage that attempted to do this, but I haven't looked at it. I'd quite like to avoid patching AppImage if I can avoid it. Basically, binary distribution on Linux is a nightmare, particularly with C++. Graphia uses newer C++ standards, which require a newer libstdc++, which is not available on older distros. I haven't used Debian for at least a decade at this point, but my recollection is that it was permanently out of date, unless you ran the bleeding edge version (sid, was it?). Essentially what I'm saying is I'm not really surprised you're having problems on Debian.

**Comment by jberryman** [comment]
`testing` generally tracks upstream closely, you don't need `sid`. That's what most people run as their desktop (unfortunately I let my self get stuck on an old stable), and seems okay for graphia
