### ISSUE TITLE
Reference and/or examples for the JSON Graph format

### ISSUE THREAD

**Issue by nsajko** [graphia-app/graphia#69]
Graphia's [manual](https://graphia.app/guide/section3/1_load_graph_data.html) documents a "JSON Graph" format as supported by Graphia, but it's not clear which format this is.

It would be nice to have:
1. a pointer to a reference for the format
2. small example graph in this format

For what it's worth, a quick Web Search leads to these two "JSON Graph" formats, and they seem to have no relation to eachother:

https://netflix.github.io/falcor/documentation/jsongraph.html

https://jsongraphformat.info

**Comment by timangus** [comment]
That's a good point; it's the latter. I should probably add links to all the specifications on that page.

**Comment by timangus** [comment]
Fixed in 94cdd4cd.
