### ISSUE TITLE
Graphia's versions

### ISSUE THREAD

**Issue by polakme** [graphia-app/graphia#81]
Hi Tim, Marta Polak here. Recently every file I am trying to open with graphia throws back version error. I have tried reinstalling from graphia.app and also from the link you shared to v5.0 in github, but everything seems to be a) converting to Graphia 3, b) giving back the same error without opening the file. 
Any suggestions?
Thanks so much
Marta
<img width="600" alt="Screenshot 2024-10-09 at 13 56 16" src="https://github.com/user-attachments/assets/8691b18f-ee08-4ca7-8ccb-3548ead2ac1d">
<img width="616" alt="Screenshot 2024-10-09 at 13 57 06" src="https://github.com/user-attachments/assets/a8b1f962-6f01-45f7-b12a-4f04d9d19db3">
<img width="846" alt="Screenshot 2024-10-09 at 13 57 12" src="https://github.com/user-attachments/assets/5e7685a9-81b4-46ac-9de8-915cda0aeb49">

**Comment by timangus** [comment]
From the About Graphia window you clearly aren't running the latest version (5.1). Probably you have 2 copies of it installed on your system somehow, and the one that you are invoking by default (from the MacOS dock?) is this old dev version. If you right click the icon and go to Options -> Show In Finder it will reveal where it's located. Remove this and then reinstall the latest version.

**Comment by polakme** [comment]
Thanks Tim!
That had worked indeed - when I was removing it previously it kept reverting to V3.
I had actually 3 versions !!! That’s a commitment and fanship, right?
Thanks again, hope you are enjoying your post JnJ live
Best
Marta


Marta E Polak
Prof of Systems Immunology

Clinical and Experimental Sciences, Faculty of Medicine, University of Southampton,
Mailpoint 813, Level E, South Block, Southampton General Hospital, Southampton, SO16 6YD, UK
https://www.southampton.ac.uk/medicine/about/staff/mep1p07.page

________________________________

**Comment by timangus** [comment]
Haha, a top fan indeed, glad you've sorted it 👍. Life's good thanks.
